name: sugar
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - pillow
  - opencv
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - pip:
    - plyfile
    - open3d
    - trimesh
    - pymcubes
    - lpips
    - scikit-image
    - imageio
# Note: After creating the environment, manually install:
#   pip install --no-build-isolation git+https://github.com/NVlabs/nvdiffrast
#   pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu118_pyt201/download.html
