name: sugar
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - pillow
  - opencv
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - pip:
    - plyfile
    - open3d
    - trimesh
    - pymcubes
    - pytorch3d
    - nvdiffrast @ git+https://github.com/NVlabs/nvdiffrast
    - lpips
    - scikit-image
    - imageio
